// <auto-generated />
using System;
using System.Collections.Generic;
using EcuNexo.Core.Tenancy;
using EcuNexo.Platform.Data.Licensing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcuNexo.Platform.Data.Licensing.Migrations
{
    [DbContext(typeof(LicensingDbContext))]
    [Migration("20260926155541_AddLicenseGrantEntitlements")]
    partial class AddLicenseGrantEntitlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("licensing")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicenseGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivationCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("activation_code_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<short>("DeploymentMode")
                        .HasColumnType("smallint")
                        .HasColumnName("deployment_mode");

                    b.PrimitiveCollection<string>("EnabledModuleCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("enabled_module_codes");

                    b.Property<DateTimeOffset?>("EntitlementsUpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("entitlements_updated_at_utc");

                    b.Property<Guid?>("EntitlementsUpdatedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("entitlements_updated_by_operator_id");

                    b.Property<int>("EntitlementsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entitlements_version");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("Generation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("generation");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("IssuedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_operator_id");

                    b.Property<int>("MaxTenants")
                        .HasColumnType("integer")
                        .HasColumnName("max_tenants");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_users");

                    b.Property<int>("MaxWarehouses")
                        .HasColumnType("integer")
                        .HasColumnName("max_warehouses");

                    b.Property<IReadOnlyList<ModuleEntitlement>>("ModuleEntitlements")
                        .HasColumnType("jsonb")
                        .HasColumnName("module_entitlements");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OnlineValidationIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("online_validation_interval_days");

                    b.Property<string>("OwnerEmailNormalized")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("owner_email_normalized");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plan_code");

                    b.Property<string>("PlanLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("plan_label");

                    b.Property<string>("PreviousPlanCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_plan_code");

                    b.Property<string>("PreviousPlanLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("previous_plan_label");

                    b.Property<Guid?>("ProvisionedTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_tenant_id");

                    b.Property<byte[]>("ProvisioningPayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("provisioning_payload_encrypted");

                    b.Property<int>("ProvisioningSlotsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("provisioning_slots_remaining");

                    b.Property<short?>("ReissueKind")
                        .HasColumnType("smallint")
                        .HasColumnName("reissue_kind");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_operator_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_grant_id");

                    b.Property<DateTimeOffset?>("SupportPeriodFromUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("support_period_from_utc");

                    b.Property<DateTimeOffset?>("SupportPeriodToUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("support_period_to_utc");

                    b.Property<DateTimeOffset?>("TrainingPeriodFromUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_period_from_utc");

                    b.Property<DateTimeOffset?>("TrainingPeriodToUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_period_to_utc");

                    b.Property<int?>("ValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("validity_days");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_license_grants");

                    b.HasIndex("ActivationCodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_license_grants_activation_code_id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_license_grants_code_hash");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_license_grants_customer_id");

                    b.HasIndex("IssuedAtUtc")
                        .HasDatabaseName("ix_license_grants_issued_at_utc");

                    b.HasIndex("IssuedByOperatorId")
                        .HasDatabaseName("ix_license_grants_issued_by_operator_id");

                    b.HasIndex("OwnerEmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_license_grants_owner_email_normalized")
                        .HasFilter("status IN (0, 2) AND owner_email_normalized IS NOT NULL");

                    b.HasIndex("PlanCode")
                        .HasDatabaseName("ix_license_grants_plan_code");

                    b.ToTable("license_grants", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicenseGrantEntitlementChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_operator_id");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.PrimitiveCollection<string>("NewEnabledModuleCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("new_enabled_module_codes");

                    b.Property<IReadOnlyList<ModuleEntitlement>>("NewEntitlements")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_entitlements");

                    b.PrimitiveCollection<string>("PreviousEnabledModuleCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_enabled_module_codes");

                    b.Property<IReadOnlyList<ModuleEntitlement>>("PreviousEntitlements")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_entitlements");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_license_grant_entitlement_changes");

                    b.HasIndex("GrantId", "ChangedAtUtc")
                        .HasDatabaseName("ix_license_grant_entitlement_changes_grant_id_changed_at_utc");

                    b.ToTable("license_grant_entitlement_changes", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicensingCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<short>("DeploymentMode")
                        .HasColumnType("smallint")
                        .HasColumnName("deployment_mode");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("customers", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicensingPlan", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.PrimitiveCollection<string>("EnabledModuleCodesDefault")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("enabled_module_codes_default");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxTenantsDefault")
                        .HasColumnType("integer")
                        .HasColumnName("max_tenants_default");

                    b.Property<int>("MaxUsersDefault")
                        .HasColumnType("integer")
                        .HasColumnName("max_users_default");

                    b.Property<int>("MaxWarehousesDefault")
                        .HasColumnType("integer")
                        .HasColumnName("max_warehouses_default");

                    b.Property<IReadOnlyList<ModuleEntitlement>>("ModuleEntitlementsDefault")
                        .HasColumnType("jsonb")
                        .HasColumnName("module_entitlements_default");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("SuggestedPriceUsdMonthly")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("suggested_price_usd_monthly");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Code")
                        .HasName("pk_plans");

                    b.ToTable("plans", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.PlatformOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_operators");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_operators_email");

                    b.ToTable("operators", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Settings.PlatformSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_platform_settings");

                    b.ToTable("platform_settings", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Training.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("AttendeeEmails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attendee_emails");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByOperatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_operator_id");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_id");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("duration_hours");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("LicenseGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_grant_id");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("modality");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_training_sessions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_training_sessions_customer_id");

                    b.HasIndex("LicenseGrantId")
                        .HasDatabaseName("ix_training_sessions_license_grant_id");

                    b.ToTable("training_sessions", "licensing");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicenseGrant", b =>
                {
                    b.HasOne("EcuNexo.Platform.Core.Licensing.LicensingCustomer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_grants_customers_customer_id");

                    b.HasOne("EcuNexo.Platform.Core.Licensing.PlatformOperator", null)
                        .WithMany()
                        .HasForeignKey("IssuedByOperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_grants_operators_issued_by_operator_id");

                    b.HasOne("EcuNexo.Platform.Core.Licensing.LicensingPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_grants_plans_plan_code");
                });

            modelBuilder.Entity("EcuNexo.Platform.Core.Licensing.LicenseGrantEntitlementChange", b =>
                {
                    b.HasOne("EcuNexo.Platform.Core.Licensing.LicenseGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_license_grant_entitlement_changes_license_grants_grant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
